LICENSE
README.md
gitops/deploy/push.yaml

Fixes #4 
Changes:
* Update license
* Update readme
* Fix source version for verify push

Getting started docs

---

gitops/README.md
gitops/build/main.yaml

Add extra build steps

---

gitops/deploy/deploy.yaml

Binary validation

---

gitops/deploy/push.yaml

Update remote image validation

---

gitops/README.md
gitops/build/main.yaml

Add hadolint docker linter

---

gitops/deploy/deploy.yaml

Pull with rebase before pushing

---

gitops/README.md
gitops/build/main.yaml

Add image scan

---

gitops/build/main.yaml

Update condition to skip on tag

---

.ci/pipeline.yaml

Sync branches

---

gitops/README.md
gitops/build/main.yaml

Pr trigger

---

packer/README.md
packer/build_image.yaml
packer/main.yaml

Packer template pipeline

---

gitops/build/main.yaml
gitops/deploy/deploy.yaml

* Use relative binary paths
* Update flux-status-cli to v0.3.0
* Fix legacy azure devops uri to work with flux-status-cli

Update binary paths and fix REPO_URI

---

gitops/deploy/deploy.yaml
gitops/deploy/main.yaml

Move condition from deployment to stage

---

terraform/apply/main.yaml
terraform/plan/main.yaml

Enable plan encryption

---

terraform/apply/main.yaml
terraform/plan/main.yaml

* Update check for encryption secret

Fix encryption check

---

packer/README.md
packer/build_image.yaml
packer/main.yaml

Packer:
* Add poolVmImage to allow using Microsoft hosted agents as well
* Update example to not trigger on changes to repo

Add poolVmImage to packer

---

gitops/README.md
gitops/build/main.yaml

GitOps:
* Add ability to enable DOCKER_BUILDKIT=1 for builds

Add flag for docker buildkit

---

gitops/build/main.yaml

GitOps:
* Change if statement for `DOCKER_BUILDKIT=1` from `true` to `True`

Update if statement

---

gitops/README.md
gitops/deploy/main.yaml
gitops/deploy/push.yaml

This change allows us to not have to build everything on our local machines while developing in complex environments

Tag and push latest in dev

---

gitops-v2/new/main.yaml
gitops-v2/promote/main.yaml
gitops-v2/status/main.yaml

Fixes https://github.com/XenitAB/gitops-promotion/issues/23

Bump gitops-promotion

---

gitops-v2/README.md

* Clarify acrNameTemplate and azureSubscriptionTemplate instructions.
* Make markdown lint happy
* Minor speeling

Update gitops-v2 README

---

packer-docker/README.md
terraform-docker/README.md

This to not keep a copy of all dockerfiles that have ran

Add --rm to docker makefile examples

---

terraform-docker/README.md
terraform-docker/apply/main.yaml
terraform-docker/plan/main.yaml

* Update the Makefile example to work with AWS,
this doesen't create any issues for none AWS users.

Create TF-docker AWS template

---

gitops-v2/build/main.yaml
gitops/build/main.yaml

Remove duplicate DOCKER_BUILD_ARGS

---

gitops-v2/new/push.yaml
gitops-v2/new/push_aws.yaml

This PR fixes the issue where gitops-v2 requires AWS azure extension even though AWS isn't used.

make aws conditional

---

.github/workflows/push-image-acr.yaml
gitops-v2-github/README.md
gitops-v2-github/push-image.yaml

This PR is a start for our github actions for the promotion flow.

GitHub workflow push img

---

.github/workflows/update-azure-devops-templates-from-upstream.yaml
README.md

This updates from upstream once per hour.

Add a default workflow for updating the imported version

---

.github/workflows/update-azure-devops-templates-from-upstream.yaml

Turns out `nil` isn't allowed here. I should have tested that "final cleanup change".

Fix broken cron job

---

gitops-v2/build/main.yaml

Change from eq to startsWith when checking branch name

Make build branch variable step more permissive

---

.ci/pipeline.yaml

Disable shallow cloning azdo cronjob pipeline

---

gitops-v2/build/main.yaml
terraform-docker/apply/main.yaml

Allow the template user to specify timeoutInMinutes. Use the same value for both the job and for the apply task to simplify (technically it could be 2 different parameters). Default value is 60 minutes which is the normal default if not specified.
I have chosen to only apply it on the terraform apply step as the other steps should be fairly quick.

Job timeout minutes
